server:
  error:
    include-message: always
    include-binging-errors: always

spring:
  datasource:
    url: jdbc:posgresql://localhost:5432/notable
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
